const Content1 = [[
    'Introduction of Hackers',
    'Computer Basics',
    'Types of Hacking Attacks',
    'Domain Basics',
    'Network Basics',
    'Types of Domains',
    'ICANN',
    'Email Security',
    'Port Scanning',
    'Information Gathering About Victim',
    'Find Open Ports',
    'Types of Virus',
    'Practical on Virus',
    'Steganography',
    'Types of Phishing',
    'Phishing',
    'Types of Sniffers',
    'Sniffing',
    'Call Spoofing',
    'Password Cracking',
    'Types of Google Dorks',
    'Website Hacking Using Google Dorks',
    'DOS and DDOS Attack',
    'Setup Honeypots',
    'Basic Sql Injections',
    'Social Engineering Attacks',
    'Finding Victims Locations',
    'Android Hacking',
    'Windows Hacking'
],
[
    'Introduction',
    'Basic of Linux',
    'Types of Wb Scanners',
    'Burp Suite in Detail',
    'Enumeration of Website',
    'OWASP Top 10',
    'Website Advance Bugs',
    'Reporting',
    'Case Study on Web Vapt',
    'Bug Bounty',
    'Mobile Application Vapt',
    'Mobile Application Vapt Reporting',
    'Reverse Engineering',
    'Network Security',
    'Metasploit in Detail',
    'Types of Firewall',
    'Network Vapt Reporting',
    'Case Study on Network Vapt',
    'Recover Deleted Files',
    'New Bugs From Our Team'
]]

export default Content1